// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "include-firstauthors-in-list": boolean;
      "first_n_authors": number;
      "include-lastauthor-in-list": boolean;
      "firstnamestyle": string;
      "namestyle": string;
      "sep-intra-author": string;
      "sep-intra-author-cjk": string;
      "sep-inter-author": string;
      "sep-omitted-authors": string;
      "indicator-for-lastauthor": string;
      "indicator-position": string;
    };
  }
}
