pref("include-firstauthors-in-list", true);
pref("first_n_authors", 1);
pref("include-lastauthor-in-list", true);
pref("firstnamestyle", "full");
pref("namestyle", "auto");
pref("sep-intra-author", " ");
pref("sep-intra-author-cjk", "");
pref("sep-inter-author", ", ");
pref("sep-omitted-authors", "...");
pref("indicator-for-lastauthor", "†");
pref("indicator-position", "after");
