name: Release on tags
run-name: GitHub Actions to release with pnpm
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build zotero plugin
        run: |
          cd ${{ github.workspace }}
          pnpm install
          pnpm run build

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            build/*.xpi
